//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "rarity")]
pub enum Rarity {
    #[sea_orm(string_value = "Common")]
    Common,
    #[sea_orm(string_value = "Rare")]
    Rare,
    #[sea_orm(string_value = "Epic")]
    Epic,
    #[sea_orm(string_value = "Legendary")]
    Legendary,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "Member")]
    Member,
    #[sea_orm(string_value = "Leader")]
    Leader,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "slot")]
pub enum Slot {
    #[sea_orm(string_value = "Head")]
    Head,
    #[sea_orm(string_value = "Chest")]
    Chest,
    #[sea_orm(string_value = "Hands")]
    Hands,
    #[sea_orm(string_value = "Legs")]
    Legs,
    #[sea_orm(string_value = "Feet")]
    Feet,
    #[sea_orm(string_value = "MainHand")]
    MainHand,
    #[sea_orm(string_value = "OffHand")]
    OffHand,
}
